### ISSUE TITLE
strip_loc.py - TypeError: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by timetraveler90** [plam4u/iOS-Playground#1]
I stumbled upon your code that could help me solve the current issue I have but I am a python newbie and tried to run it on Monterey macOS with python3 had plenty of easy to fix issues but right now I am facing the error from the title of this issue and I couldn't solve it my self, is there a chance to take a look at it and advise how can I proceed with it?

Best regards and thanks in advance.

**Comment by plam4u** [comment]
Hey, it has been some time since I worked on this. I'll check it this weekend and see what I can do. I am also on Monterey, thus I hope it is easy to reproduce. 

Thank you for using it, that little script :)

**Comment by timetraveler90** [comment]
I have managed to make it work, i have posted the code on the stackoverflow so no need to invest your time there. Thanks man, you can close this one 👍🏼
